import React from 'react';
import {
  LayoutDashboard,
  Users,
  Briefcase,
  ShoppingCart,
  FileText,
  MessageSquare,
  Settings,
  UserCircle,
  LogOut,
  ChevronDown,
  ChevronRight,
  Menu,
  X,
  FileWarning,
  FilePlus,
  Edit3,
  Trash2,
  BarChart3,
  BookOpen,
  ShieldCheck,
  LifeBuoy,
  Activity,
  Home,
  LogIn,
  UserPlus,
  Check,
  Plus as add,
} from 'lucide-react';
import { cn } from './utils';

export const Icons = {
  logo: ({ className }) => <ShieldCheck className={cn("h-8 w-8 text-primary", className)} />,
  dashboard: LayoutDashboard,
  clients: Users,
  businesses: Briefcase,
  transactions: ShoppingCart,
  complaints: FileWarning,
  onboarding: FilePlus,
  activityLogs: Activity,
  supportTickets: LifeBuoy,
  websiteContent: BookOpen,
  blogManagement: Edit3,
  reports: BarChart3,
  profile: UserCircle,
  logout: LogOut,
  settings: Settings,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  menu: Menu,
  close: X,
  add,
  edit: Edit3,
  delete: Trash2,
  home: Home,
  login: LogIn,
  register: UserPlus,
  check: Check,
  error: FileWarning,
};
